import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import RootModal from '@/components/modals/RootModal'
import { Bounce, ToastContainer } from 'react-toastify'
import OverlayLoading from '@/components/overlayLoading'

import './globals.scss'
import 'react-toastify/dist/ReactToastify.css'

const nunito = Nunito({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Relipa Shop',
  description: 'Generated by Relipa Shop',
}

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="vi">
      <body className={nunito.className}>
        <RootModal />
        <OverlayLoading />
        {children}
        <ToastContainer
          style={{ fontSize: '12px' }}
          hideProgressBar={false}
          position="bottom-left"
          newestOnTop={false}
          transition={Bounce}
          pauseOnFocusLoss
          autoClose={5000}
          theme="light"
          pauseOnHover
          closeOnClick
          rtl={false}
          draggable
        />
        <ToastContainer />
      </body>
    </html>
  )
}

export default RootLayout
